import 'dart:developer';
import 'dart:typed_data';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:either_dart/either.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:quick_resume_creator/models/quick_resume_data.dart';
import 'package:quick_resume_creator/utils/Error_handler/error_handler.dart';
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

class QuickResumeRepository {
  final currentUser = FirebaseAuth.instance.currentUser;

  Future<Either<ErrorHandler, String>> addQuickResumeData(
      QuickResumeData quickResumeData, Uint8List? customerProfileImage) async {
    final userUid = FirebaseAuth.instance.currentUser?.uid;

    try {
      CollectionReference userQuickResumeCollection = FirebaseFirestore.instance
          .collection("resume_data")
          .doc(userUid)
          .collection('user_resume');

      DocumentReference documentReference =
          await userQuickResumeCollection.add(quickResumeData.toMap());

      String autoGeneratedId = documentReference.id;

      /// Convert an `Uint8List` image to a `String` image and store it in Firebase Storage, then update the `customerProfileImage` in the Firebase Database.
      firebase_storage.Reference ref = firebase_storage.FirebaseStorage.instance
          .ref()
          .child('profile_images')
          .child(userUid!)
          .child(autoGeneratedId)
          .child('${DateTime.now().millisecondsSinceEpoch}.jpg');

      firebase_storage.UploadTask uploadTask =
          ref.putData(customerProfileImage!);

      await uploadTask.whenComplete(() async {
        String downloadURL = await ref.getDownloadURL();
        await documentReference.update({'customerProfileImage': downloadURL});
      });

      ///

      quickResumeData = quickResumeData.copyWith(resumeid: autoGeneratedId);

      await documentReference.update({'resumeid': autoGeneratedId});

      return Right(autoGeneratedId);
    } catch (e) {
      log('$e');
      return Left(ErrorHandler(message: e.toString()));
    }
  }

  Future<List<QuickResumeData>> fetchResumeData(String userId) async {
    final snapshot = await FirebaseFirestore.instance
        .collection('resume_data')
        .doc(userId)
        .collection('user_resume')
        .get();

    return snapshot.docs
        .map((doc) => QuickResumeData.fromJson(doc.data() as String))
        .toList();
  }

  void deleteResume(String resumeId) {
    FirebaseFirestore.instance
        .collection('resume_data')
        .doc(currentUser!.uid)
        .collection('user_resume')
        .doc(resumeId)
        .delete();
  }

  Future<void> updateResume(String resumeId, QuickResumeData resumeData) async {
    try {
      await FirebaseFirestore.instance
          .collection('resume_data')
          .doc(currentUser!.uid)
          .collection('user_resume')
          .doc(resumeId)
          .update(resumeData.toMap());
      log('Resume updated successfully');
    } catch (e) {
      log('Error updating resume data: $e');
    }
  }
}
